

export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored just for you",
    description:
    "Get interview questions and model answers based on your role, experience, and specific focus areas.",
  },

  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
    "Expand answers only when you're ready, Dive deeper into any concept instantly with AI-powered detailed explaination and examples.",
  },
  {
    id: "03",
    title: "Capture your insights",
    description:
    "Add personal notes to each question and pin important once to the top - making your learning more organized and effective.",

  },
  {
    id: "04",
    title: 'Understand the "why" behind every answer',
    description:
    "Beyond just answers - unlock detailed concept explanations generated by AI to truly grasp the underlying principles and reasoning.",
  },
  {
    id: "05",
    title: "Save, organize and Revisit",
    description:
    "Easily save your interview sets , organize them neatly in your dashboard , and pick up your preperation right where you left off.",
  },
];